# Generated by Django 2.2.26 on 2022-01-17 12:37

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('courses', jsonfield.fields.JSONField()),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('graduate', models.DateField(blank=True, null=True)),
                ('grade', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RunSQL("insert into accounts_gender (name) values ('Male'),('Female')")
    ]
