# Generated by Django 2.2.26 on 2022-01-18 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('MRN', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_admitted', models.DateField(auto_now_add=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_date', models.DateField(auto_now_add=True)),
                ('lastUpdate', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Test')),
            ],
        ),
        migrations.RunSQL(
            """
            insert into accounts_gender (name) values ('Male'),('Female'),('Non-Specified');
            insert into accounts_test (name) values ('WES - Ion'),('Exome Sequencing');
            """
        )
    ]
