# Generated by Django 2.2.26 on 2022-01-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
