# Generated by Django 2.2.26 on 2022-01-18 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(choices=[('Blood', 'Blood'), ('DNA', 'DNA')], default='', max_length=50, verbose_name='Sample Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_admitted',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Gender', verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Patient Name'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_date',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Test', verbose_name='Test'),
        ),
    ]
