# Generated by Django 2.2.26 on 2022-01-19 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_admitted', models.DateField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(max_length=50, verbose_name='Patient Name')),
                ('MRN', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='test_app.Gender', verbose_name='Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RequestedTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_date', models.DateField(auto_created=True, auto_now_add=True)),
                ('sample_type', models.CharField(choices=[('Blood', 'Blood'), ('DNA', 'DNA')], max_length=50, verbose_name='Sample Type')),
                ('lastUpdate', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_app.Test', verbose_name='Test')),
            ],
        ),

    ]
