# Generated by Django 2.2.26 on 2022-01-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
            insert into test_app_gender (name) VALUES ('Male'),('Female'),('Non-Specified');
            insert into test_app_test (name) VALUES ('Test 1'),('Test 2'),('Test 3');
            """)
    ]
